#import "AITrainerBridge.h"
#import <React/RCTLog.h>

// Import Rust C headers (will be generated by cbindgen)
#include "ai_trainer.h"

@implementation AITrainerBridge

RCT_EXPORT_MODULE(AITrainer);

RCT_EXPORT_METHOD(initialize:(NSString *)apiKey
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)
{
  const char *api_key_c = [apiKey UTF8String];

  // Initialize Rust trainer
  int result = rust_init_trainer(api_key_c);

  if (result == 0) {
    resolve(@{@"success": @YES});
  } else {
    reject(@"INIT_ERROR", @"Failed to initialize AI trainer", nil);
  }
}

RCT_EXPORT_METHOD(startTraining:(NSString *)filePath
                  model:(NSString *)model
                  epochs:(NSInteger)epochs
                  batchSize:(nullable NSNumber *)batchSize
                  learningRate:(nullable NSNumber *)learningRate
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)
{
  const char *file_path_c = [filePath UTF8String];
  const char *model_c = [model UTF8String];

  int batch = batchSize ? [batchSize intValue] : -1;
  double lr = learningRate ? [learningRate doubleValue] : -1.0;

  char *result = rust_start_training(file_path_c, model_c, (int)epochs, batch, lr);

  if (result != NULL) {
    NSString *resultStr = [NSString stringWithUTF8String:result];
    rust_free_string(result);
    resolve(resultStr);
  } else {
    reject(@"TRAINING_ERROR", @"Failed to start training", nil);
  }
}

RCT_EXPORT_METHOD(getJobStatus:(NSString *)jobId
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)
{
  const char *job_id_c = [jobId UTF8String];

  char *result = rust_get_job_status(job_id_c);

  if (result != NULL) {
    NSString *resultStr = [NSString stringWithUTF8String:result];
    rust_free_string(result);
    resolve(resultStr);
  } else {
    reject(@"STATUS_ERROR", @"Failed to get job status", nil);
  }
}

RCT_EXPORT_METHOD(listJobs:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)
{
  char *result = rust_list_jobs();

  if (result != NULL) {
    NSString *resultStr = [NSString stringWithUTF8String:result];
    rust_free_string(result);
    resolve(resultStr);
  } else {
    reject(@"LIST_ERROR", @"Failed to list jobs", nil);
  }
}

RCT_EXPORT_METHOD(cancelJob:(NSString *)jobId
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)
{
  const char *job_id_c = [jobId UTF8String];

  char *result = rust_cancel_job(job_id_c);

  if (result != NULL) {
    NSString *resultStr = [NSString stringWithUTF8String:result];
    rust_free_string(result);
    resolve(resultStr);
  } else {
    reject(@"CANCEL_ERROR", @"Failed to cancel job", nil);
  }
}

RCT_EXPORT_METHOD(testModel:(NSString *)model
                  prompt:(NSString *)prompt
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)
{
  const char *model_c = [model UTF8String];
  const char *prompt_c = [prompt UTF8String];

  char *result = rust_test_model(model_c, prompt_c);

  if (result != NULL) {
    NSString *resultStr = [NSString stringWithUTF8String:result];
    rust_free_string(result);
    resolve(resultStr);
  } else {
    reject(@"TEST_ERROR", @"Failed to test model", nil);
  }
}

RCT_EXPORT_METHOD(validateData:(NSString *)filePath
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)
{
  const char *file_path_c = [filePath UTF8String];

  int result = rust_validate_data(file_path_c);

  if (result == 0) {
    resolve(@{@"valid": @YES});
  } else if (result == 1) {
    resolve(@{@"valid": @NO});
  } else {
    reject(@"VALIDATION_ERROR", @"Failed to validate data", nil);
  }
}

@end
